/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

/**
 * Attributes for fetching answers for a contact question
 */
export interface AnswersInput {
  survey_id: string;
  area_id: string;
  start_date?: string | null;
  end_date?: string | null;
}

/**
 * Attributes for fetching areas for a branch
 */
export interface BranchInput {
  branch_id: string;
}

/**
 * Attributes for fetching branches for a company
 */
export interface CompanyInput {
  company_id: string;
}

/**
 * Autogenerated input type of CreateArea
 */
export interface CreateAreaInput {
  name: string;
  branch_id: string;
  friendly_token?: string | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of CreateBranch
 */
export interface CreateBranchInput {
  name: string;
  address: string;
  company_id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of CreateQuestion
 */
export interface CreateQuestionInput {
  text: string;
  type: string;
  duration: number;
  description?: string | null;
  satisfaction_index?: number | null;
  subtype?: number | null;
  survey_id: string;
  multiple_choice_answers?: string[] | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of CreateSurvey
 */
export interface CreateSurveyInput {
  name: string;
  company_id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of CreateUser
 */
export interface CreateUserInput {
  email: string;
  first_name?: string | null;
  last_name?: string | null;
  username?: string | null;
  web?: boolean | null;
  area_id?: string | null;
  password: string;
  password_confirmation: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteActiveSurvey
 */
export interface DeleteActiveSurveyInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteAdminUser
 */
export interface DeleteAdminUserInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteArea
 */
export interface DeleteAreaInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteBranch
 */
export interface DeleteBranchInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteQuestion
 */
export interface DeleteQuestionInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteSurvey
 */
export interface DeleteSurveyInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of DeleteUser
 */
export interface DeleteUserInput {
  id: string;
  clientMutationId?: string | null;
}

/**
 * Attributes for fetching answers for a question
 */
export interface QuestionsAnswersInput {
  survey_id: string;
  area_id: string[];
  start_date: string;
  finish_date: string;
}

/**
 * Autogenerated input type of RegisterAdminUser
 */
export interface RegisterAdminUserInput {
  email: string;
  password: string;
  type: string;
  company_id?: string | null;
  areas_ids?: string[] | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of SignIn
 */
export interface SignInInput {
  email: string;
  password: string;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of SignOut
 */
export interface SignOutInput {
  clientMutationId?: string | null;
}

/**
 * Attributes for fetching questions for a survey
 */
export interface SurveyInput {
  survey_id: string;
}

/**
 * Attributes for fetching answers for a text question
 */
export interface TextAnswersInput {
  survey_id: string;
  question_id: string;
  area_id: string;
  start_date: string;
  end_date: string;
}

/**
 * Autogenerated input type of UpdateAdminUser
 */
export interface UpdateAdminUserInput {
  email?: string | null;
  password?: string | null;
  password_confirmation?: string | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateArea
 */
export interface UpdateAreaInput {
  id: string;
  name?: string | null;
  survey_id?: string | null;
  friendly_token?: string | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateBranch
 */
export interface UpdateBranchInput {
  id: string;
  name?: string | null;
  address?: string | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateCompanyAdminUser
 */
export interface UpdateCompanyAdminUserInput {
  id: string;
  email?: string | null;
  areas_ids?: string[] | null;
  type?: string | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateQuestion
 */
export interface UpdateQuestionInput {
  id: string;
  text?: string | null;
  duration?: number | null;
  description?: string | null;
  satisfaction_index?: number | null;
  subtype?: number | null;
  multiple_choice_answers?: string[] | null;
  position?: number | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateSurvey
 */
export interface UpdateSurveyInput {
  id: string;
  name?: string | null;
  clientMutationId?: string | null;
}

/**
 * Autogenerated input type of UpdateUser
 */
export interface UpdateUserInput {
  id: string;
  email?: string | null;
  first_name?: string | null;
  last_name?: string | null;
  username?: string | null;
  web?: boolean | null;
  area_id?: string | null;
  password?: string | null;
  password_confirmation?: string | null;
  clientMutationId?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
