name: Jenkins Action
# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches:
      - develop
    types: [closed]
    
jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://ec2-54-189-150-153.us-west-2.compute.amazonaws.com:8080"
        user: "effectus"
        token: ${{secrets.TOKEN}}
        job: "Askme UI Automation"

