name: Super-Linter
# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://ec2-54-189-150-153.us-west-2.compute.amazonaws.com:8080/"
        user: "effectus"
        token: ${{'11a8110239140df4f6572423febd7fcd14
'}}
        job: "Askme UI Automation"
      # Runs the Super-Linter action
#       - name: Run Super-Linter
#         uses: github/super-linter@v3
#         env:
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
